### ISSUE TITLE
Step does not properly escape spaces in dSym path

### ISSUE THREAD

**Issue by jmelliadis** [alexshikov/bitrise-step-appcenter-dsym-upload#1]
I am using this step in our Xamarin.iOS workflow and it appears that the step is not properly escaping spaces in the dSym file path. Output from one of our builds:

+------------------------------------------------------------------------------+

| (10) appcenter-dsym-upload@0.1.2                                             |
+------------------------------------------------------------------------------+
| id: appcenter-dsym-upload                                                    |
| version: 0.1.2                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: bash                                                                |
| time: 2018-02-16T15:28:38-08:00                                              |
+------------------------------------------------------------------------------+
|                                                                              |
INFO[15:28:38]  * [OK] Step dependency (node) installed, available. 
+ hash appcenter
+ echo 'Microsoft AppCenter CLI is not installed. Installing...'
Microsoft AppCenter CLI is not installed. Installing...
+ npm install -g appcenter-cli
/usr/local/bin/appcenter -> /usr/local/lib/node_modules/appcenter-cli/bin/appcenter.js
+ appcenter-cli@1.0.11
added 228 packages in 10.502s
+ envman add --key BITRISE_DSYM_PATH
+ appcenter crashes upload-symbols -s /Users/vagrant/deploy/iSurvey.iOS 2-16-18 3.23 PM.dSYM.zip -a {account/app} --token {token} --quiet
Error: Command 'crashes upload-symbols -s /Users/vagrant/deploy/iSurvey.iOS 2-16-18 3.23 PM.dSYM.zip -a {account/app} --token {token} --quiet' failed with exception "Unknown arguments: 2-16-18 3.23 PM.dSYM.zip"
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | appcenter-dsym-upload@0.1.2 (exit code: 3)                    | 17 sec   |
+---+---------------------------------------------------------------+----------+
| Issue tracker: ...b.com/alexshikov/bitrise-step-appcenter-dsym-upload/issues |
| Source: https://github.com/alexshikov/bitrise-step-appcenter-dsym-upload     |
+---+---------------------------------------------------------------+----------+

**Comment by alexshikov** [comment]
@jmelliadis thanks you for reporting! The issue should be fixed in 0.1.3
