### ISSUE TITLE
Environment variable being overwritten

### ISSUE THREAD

**Issue by Kymer** [alexshikov/bitrise-step-appcenter-dsym-upload#4]
I had an issue where reading the `$BITRISE_DSYM_PATH` environment variable _after_ this step ran in my workflow it returned an empty string. I noticed the [following line](https://github.com/alexshikov/bitrise-step-appcenter-dsym-upload/blob/e3236796b6d6b93a04b16a16ec3b4fcd87f9470d/step.sh#L12) `envman add --key BITRISE_DSYM_PATH`. It seems like that overwrites the value, no? Is this somehow intentional?

I'd be happy to create a PR, but first wanted to check I'm not going crazy and  might be misunderstanding something, somehow hah.

**Comment by alexshikov** [comment]
Hi @Kymer that's a good question. I don't remember the reason of adding this line. It's either a copy paste from another example, or this line was required to make the script work :)

If you have a fix on your mind and you could test it, I would be glad to accept the PR.
